#####################################
# Don't touch this file is generated 
# expecilly for: vision
###################################
#
# Consider to Backup  /home/tom/devstack-data
#
version: "3"
services: 
  ngnix:
     build: nginx-reverse
     ports: 
       - "80:80"       #http:// 
       # SSH Bypassing into gitlab, if you want to change this edit nginx.conf also
       - "2222:2222"   #ssh port of gitlab (ssh://git@myhostname:2222/scott/foo.git)
       - "5555:5555"   #Gitlab Docker Registry do NOT use 5000, this is an internal PORT of the gitlab-ce Image
  jenkins-fat:
    build: jenkins-fat
    dns: 192.168.178.1
    volumes:
      - /home/tom/devstack-data/jenkins:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock
  sonar-db:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /home/tom/devstack-data/sonar-db/postgresql:/var/lib/postgresql
      # This needs explicit mapping due to 
      # https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - /home/tom/devstack-data/sonar-db/postgresql_data:/var/lib/postgresql/data
  sonar:
    image: sonarqube
    dns: 192.168.178.1
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
    volumes:
      - /home/tom/devstack-data/sonar/sonarqube_conf:/opt/sonarqube/conf
      - /home/tom/devstack-data/sonar/sonarqube_data:/opt/sonarqube/data
      - /home/tom/devstack-data/sonar/sonarqube_extensions:/opt/sonarqube/extensions
      - /home/tom/devstack-data/sonar/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    dns: 192.168.178.1
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://vision/gitlab'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        # docker-registry config
        registry_external_url 'https://vision:5555'
        registry_nginx['listen_port'] = 5555
        registry_nginx['listen_https'] = true
        # SSL config just for the docker-registry need
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/vision.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/vision.key"
        registry_nginx['proxy_set_headers'] = {
        "X-Forwarded-Proto" => "https",
        "X-Forwarded-Ssl" => "on"
        }
    volumes:
      - /home/tom/devstack-data/gitlab/config:/etc/gitlab
      - /home/tom/devstack-data/gitlab/logs:/var/log/gitlab
      - /home/tom/devstack-data/gitlab/data:/var/opt/gitlab
  
  gitlabrunner:
    build: gitlabrunner
    dns: 192.168.178.1
    environment:
      - DOCKER_DNS=192.168.178.1
      - GITLAB_URL=http://vision/gitlab
      - REGISTER_TOKEN=s3cretToken4Runner
      - REGISTER_MODE=KEEP #KEEP register a new runner an keep it. FRESH unregister all runners and always install a new (pipeline-history lost!)
      - REGISTER_TRYS=60 # every 5 seconds a try to register the runner..gitlab takes a long time to startup
    volumes:
      - /home/tom/devstack-data/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
  
  nexus:
    image: sonatype/nexus3
    dns: 192.168.178.1
    environment:
      - NEXUS_CONTEXT=nexus
    volumes:
      - /home/tom/devstack-data/nexus:/nexus-data   
      
  
